server:
  port: 8098
  servlet:
    context-path: /
spring:
  mail:
    host: smtp.163.com
    username: 13272784073@163.com
    password: huang098215
    default-encoding: utf-8
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root